# Generated by Django 4.2.1 on 2023-07-21 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("laitrr_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="account",
            unique_together=set(),
        ),
    ]
