# Generated by Django 4.2.1 on 2023-07-21 00:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("laitrr_auth", "0002_alter_account_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("provider", "provider_account_id")},
        ),
    ]
