# Generated by Django 4.2.1 on 2023-07-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laitrr_auth", "0003_alter_account_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="session_token",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
