# Generated by Django 4.2.1 on 2023-07-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="oauth_profile_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
